const poc5={compute:false,digital:false,railCapacity:false,ports:false,dnspSignals:false,waterExpanded:false};
function visiblePair(id,on){setVisible(`${id}-dots`,on);setVisible(`${id}-labels`,on)}
function addPoc5Points(id,data,color,visible=false,radius=7,labelZoom=7){map.addSource(id,{type:'geojson',data});map.addLayer({id:`${id}-dots`,type:'circle',source:id,minzoom:4,layout:{visibility:visible?'visible':'none'},paint:{'circle-radius':['interpolate',['linear'],['zoom'],4,radius-2,10,radius+2],'circle-color':color,'circle-opacity':0.92,'circle-stroke-color':'#101820','circle-stroke-width':2}});map.addLayer({id:`${id}-labels`,type:'symbol',source:id,minzoom:labelZoom,layout:{visibility:visible?'visible':'none','text-field':['get','name'],'text-size':11,'text-offset':[0,1.2],'text-anchor':'top','text-allow-overlap':false,'text-padding':4},paint:{'text-color':'#fff','text-halo-color':'#17232b','text-halo-width':2}});wireClick(`${id}-dots`);wireClick(`${id}-labels`)}
function addCompute(data){map.addSource('compute',{type:'geojson',data});map.addLayer({id:'compute-dots',type:'circle',source:'compute',minzoom:4,layout:{visibility:'none'},paint:{'circle-radius':['interpolate',['linear'],['coalesce',['to-number',['get','capacity_mw']],1],1,5,50,7,150,9,400,12,600,14],'circle-color':'#54d2ff','circle-opacity':0.9,'circle-stroke-color':'#10212a','circle-stroke-width':2}});map.addLayer({id:'compute-labels',type:'symbol',source:'compute',minzoom:7,layout:{visibility:'none','text-field':['get','name'],'text-size':11,'text-offset':[0,1.25],'text-anchor':'top','text-allow-overlap':false},paint:{'text-color':'#fff','text-halo-color':'#17232b','text-halo-width':2}});wireClick('compute-dots');wireClick('compute-labels')}
function addGeneralisedLines(id,data,color,dash){map.addSource(id,{type:'geojson',data});map.addLayer({id,type:'line',source:id,minzoom:4,layout:{visibility:'none'},paint:{'line-color':color,'line-width':['interpolate',['linear'],['zoom'],4,2,10,4],'line-opacity':0.8,'line-dasharray':dash}});wireClick(id)}
function addExpandedWater(data){const ids=['WAT-TOOWOOMBA','WAT-LOWER-HUNTER','WAT-TAMWORTH','WAT-ARMIDALE'];map.addSource('water-expanded',{type:'geojson',data});const filter=['in',['get','entity_id'],['literal',ids]];map.addLayer({id:'water-expanded-dots',type:'circle',source:'water-expanded',filter,minzoom:4,layout:{visibility:'none'},paint:{'circle-radius':9,'circle-color':'#2bd9c4','circle-opacity':0.92,'circle-stroke-color':'#10212a','circle-stroke-width':2}});map.addLayer({id:'water-expanded-labels',type:'symbol',source:'water-expanded',filter,minzoom:6,layout:{visibility:'none','text-field':['get','name'],'text-size':11,'text-offset':[0,1.2],'text-anchor':'top'},paint:{'text-color':'#fff','text-halo-color':'#17232b','text-halo-width':2}});wireClick('water-expanded-dots');wireClick('water-expanded-labels')}
function appendPoc5Legend(){const el=document.getElementById('legendPanel');if(!el)return;let h='';if(poc5.compute)h+=dot('#54d2ff','Compute / data-centre campus');if(poc5.digital)h+=`<div class="legend-row"><span class="legend-swatch" style="background:#7f8cff"></span><span>Generalised digital backbone corridor</span></div>`;if(poc5.railCapacity)h+=`<div class="legend-row"><span class="legend-swatch" style="background:#ffcf5c"></span><span>Rail capacity / investment corridor</span></div>`;if(poc5.ports)h+=dot('#ff9f68','Port system / catchment anchor');if(poc5.dnspSignals)h+=dot('#d98cff','DNSP capacity / augmentation signal');if(poc5.waterExpanded)h+=dot('#2bd9c4','New regional water-system evidence');if(h)el.insertAdjacentHTML('beforeend','<div class="legend-divider"></div><div class="legend-sub">POC-005 additions</div>'+h)}
const baseLegend=updateLegend;updateLegend=function(){baseLegend();appendPoc5Legend()}
async function loadPoc5(){try{const [compute,digital,railCap,ports,dnsp,waterEx]=await Promise.all([j('./data/compute_campuses.geojson'),j('./data/digital_backbone.geojson'),j('./data/rail_capacity_investment.geojson'),j('./data/ports.geojson'),j('./data/dnsp_capacity_signals.geojson'),j('./data/water_systems_expanded.geojson')]);addCompute(compute);addGeneralisedLines('digital-backbone',digital,'#7f8cff',[3,2]);addGeneralisedLines('rail-capacity',railCap,'#ffcf5c',[2,1]);addPoc5Points('ports',ports,'#ff9f68',false,9,6);addPoc5Points('dnsp-signals',dnsp,'#d98cff',false,8,7);addExpandedWater(waterEx);document.getElementById('buildNote').textContent+=` · POC-005 ${compute.features.length} compute · ${digital.features.length} digital · ${railCap.features.length} rail-capacity · ${ports.features.length} ports`;updateLegend();}catch(e){console.error('POC-005 layers',e);document.getElementById('buildNote').textContent='POC-005 data missing — run: python tools/build_map_poc005.py'}}
map.on('load',loadPoc5);
function bindPoc5(id,key,fn){document.getElementById(id).addEventListener('change',e=>{poc5[key]=e.target.checked;fn(e.target.checked);updateLegend()})}
bindPoc5('compute','compute',on=>visiblePair('compute',on));bindPoc5('digital','digital',on=>setVisible('digital-backbone',on));bindPoc5('railCapacity','railCapacity',on=>setVisible('rail-capacity',on));bindPoc5('ports','ports',on=>visiblePair('ports',on));bindPoc5('dnspSignals','dnspSignals',on=>visiblePair('dnsp-signals',on));bindPoc5('waterExpanded','waterExpanded',on=>{setVisible('water-expanded-dots',on);setVisible('water-expanded-labels',on)});
