// POC-008 focal evidence layers. Existing VECA layers remain context only.
state.popmode='none';state.rail=false;state.roads=false;state.transmission=false;state.rez=false;state.capital=false;
let routeEnabled=true,tenureEnabled=true,urbanEnabled=true;
const ROLE_COLOURS={hard_exclusion:'#7b1fa2',very_high_penalty:'#d32f2f',soft_penalty:'#f57c00',neutral_evidence:'#90a4ae',positive_preference:'#00a67e'};
const ROUTE_COLOURS={at_grade:'#2bd9c5',embankment:'#d7c14b',cutting:'#f28c45',bridge_or_elevated:'#ef5da8',tunnel:'#8b6bd6'};
function roleColour(){return ['match',['get','rule_role'],'hard_exclusion',ROLE_COLOURS.hard_exclusion,'very_high_penalty',ROLE_COLOURS.very_high_penalty,'soft_penalty',ROLE_COLOURS.soft_penalty,'neutral_evidence',ROLE_COLOURS.neutral_evidence,'positive_preference',ROLE_COLOURS.positive_preference,'#777'];}
function routeColour(){return ['match',['get','construction_mode'],'at_grade',ROUTE_COLOURS.at_grade,'embankment',ROUTE_COLOURS.embankment,'cutting',ROUTE_COLOURS.cutting,'bridge_or_elevated',ROUTE_COLOURS.bridge_or_elevated,'tunnel',ROUTE_COLOURS.tunnel,'#fff'];}
function setLayer(id,on){if(map.getLayer(id))map.setLayoutProperty(id,'visibility',on?'visible':'none')}
function showLand(f){const p=f.properties||{};document.getElementById('detailContent').innerHTML=`<div class="eyebrow">POC-008 · ${String(p.rule_role||'evidence').replaceAll('_',' ')}</div><h2>${String(p.factor_class||p.source_class||'Land evidence').replaceAll('_',' ')}</h2><dl class="detail-grid"><dt>Source</dt><dd>${p.source_id||'—'}</dd><dt>Jurisdiction</dt><dd>${p.jurisdiction||'—'}</dd><dt>Source class</dt><dd>${p.source_class||'—'}</dd><dt>Source subtype</dt><dd>${p.source_type||'—'}</dd><dt>Rule role</dt><dd>${p.rule_role||'—'}</dd><dt>Diagnostic weight</dt><dd>${p.rule_weight??'—'}</dd></dl><div class="section-title">Why?</div><div class="interpretation">${p.rule_rationale||'No rule rationale recorded.'}</div><div class="section-title">Guardrail</div><div class="interpretation">This role is a POC screening lever, not a legal, acquisition or engineering determination. Public ownership is not automatically favourable.</div>`;}
function showRoute(f){const p=f.properties||{};document.getElementById('detailContent').innerHTML=`<div class="eyebrow">POC-007 · SEGMENT ${p.segment_id??'—'}</div><h2>${String(p.construction_mode||'route segment').replaceAll('_',' ')}</h2><dl class="detail-grid"><dt>Length</dt><dd>${p.length_km??'—'} km</dd><dt>Chainage</dt><dd>${p.chainage_start_km??'—'}–${p.chainage_end_km??'—'} km</dd><dt>Terrain slope P90</dt><dd>${p.terrain_slope_p90_deg??'—'}°</dd><dt>Mean grade</dt><dd>${p.mean_grade_pct??'—'}%</dd></dl><div class="section-title">POC-008 question</div><div class="interpretation">What ownership, urban fabric, reservation and infrastructure conflicts does this terrain-selected segment encounter?</div>`;}
async function optionalJson(url){try{const r=await fetch(url);if(!r.ok)return null;return await r.json()}catch(e){return null}}
function addEvidence(name,data,visible,opacity){if(!data)return false;map.addSource(name,{type:'geojson',data});map.addLayer({id:`${name}-fill`,type:'fill',source:name,layout:{visibility:visible?'visible':'none'},paint:{'fill-color':roleColour(),'fill-opacity':opacity,'fill-outline-color':'rgba(255,255,255,0.16)'}});map.on('click',`${name}-fill`,e=>{if(e.features?.[0])showLand(e.features[0])});map.on('mouseenter',`${name}-fill`,()=>map.getCanvas().style.cursor='pointer');map.on('mouseleave',`${name}-fill`,()=>map.getCanvas().style.cursor='');return true;}
map.on('load',async()=>{
  const [route,tenure,urban,summary]=await Promise.all([
    optionalJson('../poc-007/data/hst_terrain_segments.geojson'),
    optionalJson('./data/land_tenure_nsw.geojson'),
    optionalJson('./data/urban_meshblocks.geojson'),
    optionalJson('./data/land_corridor_summary.json')]);
  if(route){map.addSource('poc008-route-src',{type:'geojson',data:route});map.addLayer({id:'poc008-route-case',type:'line',source:'poc008-route-src',paint:{'line-color':'#101820','line-width':['interpolate',['linear'],['zoom'],4,4,10,10],'line-opacity':0.9}});map.addLayer({id:'poc008-route',type:'line',source:'poc008-route-src',paint:{'line-color':routeColour(),'line-width':['interpolate',['linear'],['zoom'],4,2.4,10,6.5],'line-opacity':0.98}});map.on('click','poc008-route',e=>{if(e.features?.[0])showRoute(e.features[0])});map.on('mouseenter','poc008-route',()=>map.getCanvas().style.cursor='pointer');map.on('mouseleave','poc008-route',()=>map.getCanvas().style.cursor='');}
  const hasTenure=addEvidence('poc008-tenure',tenure,tenureEnabled,0.30);
  const hasUrban=addEvidence('poc008-urban',urban,urbanEnabled,0.42);
  const roles=Object.entries(ROLE_COLOURS).map(([k,c])=>`<div class="legend-row"><span class="legend-swatch" style="background:${c}"></span><span>${k.replaceAll('_',' ')}</span></div>`).join('');document.getElementById('legendPanel').innerHTML=`<div class="legend-title">POC-008 rule roles</div>${roles}`;
  const status=[];status.push(hasTenure?'NSW tenure loaded':'NSW tenure not built');status.push(hasUrban?'urban Mesh Blocks loaded':'urban Mesh Blocks not built');if(summary?.poc007_path_intersections?.length)status.push(`${summary.poc007_path_intersections.length} factor classes intersect route`);document.getElementById('landStatus').textContent=status.join(' · ');document.getElementById('buildNote').textContent='POC-008 · explainable land/corridor evidence · route unchanged';
});
document.getElementById('routeVisible').addEventListener('change',e=>{routeEnabled=e.target.checked;setLayer('poc008-route',routeEnabled);setLayer('poc008-route-case',routeEnabled)});document.getElementById('tenureVisible').addEventListener('change',e=>{tenureEnabled=e.target.checked;setLayer('poc008-tenure-fill',tenureEnabled)});document.getElementById('urbanVisible').addEventListener('change',e=>{urbanEnabled=e.target.checked;setLayer('poc008-urban-fill',urbanEnabled)});
